# yaml-language-server: $schema=https://json.schemastore.org/electron-builder.json

appId: com.hexapod.app
productName: Hexapod
publish: null
directories:
  app: ./dist/
  output: ./out/
mac:
  target: dmg
  identity: null # change this to your signing identity
  icon: build/icon.icns
win:
  target: portable
  asar: true
  icon: build/icon.ico
linux:
  target: AppImage
  icon: icons/appIcon.png
  category: Utility
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
buildVersion: "1"
