appId: com.hexapod.app
productName: Hexapod
directories:
  app: ./dist/
  output: ./out/
mac:
  target: dmg
  identity: null # change this to your signing identity
  icon: build/icon.icns
win:
  target: portable
  asar: true
  icon: build/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
buildVersion: "1"
