# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Executables

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-executables:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node env
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Transpile, build and dist electron bundles
        run: |
          npm i -g yarn
          yarn install
          yarn run prod
          yarn run build

      - name: Create Release with Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/*.exe
            out/*.dmg
            out/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
