name: Build Executables

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  greeting:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node env
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Transpile, build and dist electron bundles
        run: |
          npm i -g yarn
          yarn install
          yarn run quickbuild

      - name: Create Release with Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/*.exe
            out/*.dmg
            out/mac/*.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
