# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Executables

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:
    
      - "v*.*.*-*"
      - "v*.*.*-*.*"
  pull_request:
    branches:    
      - master


jobs:
  build-executables:
    strategy:
      matrix:
        os: [macos-11, windows-2019, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node env
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Transpile, build and dist electron bundles
        run: |
          npm i -g yarn
          yarn install
          yarn run prod
          yarn run build

      - name: Create Release with Artifacts
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' # only run on tag push events
        with:
          files: |
            out/*.exe
            out/*.dmg
            out/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
