# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Executables

on:
  push:
    tags:
      - "v*.*.*"
<<<<<<< HEAD
  workflow_dispatch:
    
=======
      - "v*.*.*-*"
      - "v*.*.*-*.*"
  pull_request:
    branches:    
      - master
>>>>>>> 63568a3c29f6aa3c2fea6b3733e504c4bf4e0fe1

jobs:
  build-executables:
    strategy:
      matrix:
<<<<<<< HEAD
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false
=======
        os: [macos-11, windows-2019, ubuntu-20.04]
>>>>>>> 63568a3c29f6aa3c2fea6b3733e504c4bf4e0fe1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node env
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Transpile, build and dist electron bundles
        run: |
          npm i -g yarn
          yarn install
          yarn run prod
          yarn run build

      - name: Create Release with Artifacts
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' # only run on tag push events
        with:
          files: |
            out/*.exe
            out/*.dmg
            out/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
