# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

on:
  pull_request:
    branches:    
      - master

jobs:
  build-executables:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node env
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Transpile, build and dist electron bundles
        run: |
          npm i -g yarn
          yarn install
          yarn lint